import { generateDocument, generateEmail, startStripeCheckout, startPaystackCheckout, checkBackend } from './api.js';
import { renderDocument, renderEmail } from './ui.js';

// ── State ─────────────────────────────────────────────────
let docType = 'invoice';
let lines   = [];
let generatedEmail = '';

// ── Init ──────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', async () => {
  addLine();
  showSection('dashboard');

  // Check backend connectivity
  const ok = await checkBackend();
  const banner = document.getElementById('backend_banner');
  if (banner) banner.style.display = ok ? 'none' : 'flex';
});

// ── Navigation ────────────────────────────────────────────
window.showSection = (s) => {
  ['dashboard','create'].forEach(id => {
    document.getElementById('section-' + id).style.display = 'none';
  });
  document.getElementById('section-' + s).style.display = s === 'create' ? 'grid' : 'block';
};

// ── Doc type toggle ───────────────────────────────────────
window.switchType = (type, el) => {
  docType = type;
  document.querySelectorAll('.type-tabs .tab').forEach(t => t.classList.remove('active'));
  el.classList.add('active');
  document.getElementById('line_items_section').style.display = type === 'invoice' ? 'block' : 'none';
  document.getElementById('scope_section').style.display     = type === 'proposal' ? 'block' : 'none';
};

// ── Line items ────────────────────────────────────────────
window.addLine = (desc = '', qty = 1, price = 0) => {
  const id = Date.now() + Math.random();
  lines.push({ id, desc, qty, price });
  renderLines();
};

window.removeLine = (id) => {
  lines = lines.filter(l => l.id !== id);
  renderLines();
};

window.updateLine = (id, field, val) => {
  const l = lines.find(x => x.id === id);
  if (l) l[field] = field === 'desc' ? val : parseFloat(val) || 0;
};

function renderLines() {
  const container = document.getElementById('line_rows');
  container.innerHTML = '';
  lines.forEach(line => {
    const row = document.createElement('div');
    row.className = 'line-row';
    row.innerHTML = `
      <input value="${line.desc}" placeholder="Service description" oninput="updateLine(${line.id},'desc',this.value)" />
      <input value="${line.qty}" type="number" min="1" oninput="updateLine(${line.id},'qty',this.value)" />
      <input value="${line.price}" type="number" min="0" placeholder="0.00" oninput="updateLine(${line.id},'price',this.value)" />
      <button class="del-btn" onclick="removeLine(${line.id})">×</button>`;
    container.appendChild(row);
  });
}

function getTotal()     { return lines.reduce((s, l) => s + l.qty * l.price, 0); }
function getTax(total)  { return Math.round(total * 0.10 * 100) / 100; }

// ── Generate ──────────────────────────────────────────────
window.generateDoc = async () => {
  const btn = document.getElementById('gen_btn');
  btn.disabled = true;
  btn.innerHTML = '<div class="spinner"></div> AI is writing...';

  const fields = {
    fromName: val('from_name'), fromEmail: val('from_email'), fromPhone: val('from_phone'),
    toName:   val('to_name'),   toEmail:   val('to_email'),
    projectTitle: val('project_title'), currency: val('currency'),
    dueDate:  val('due_date'), extraNotes: val('extra_notes'),
    scopeText: val('scope_text'),
  };

  const total     = getTotal();
  const tax       = getTax(total);
  const grandTotal = Math.round((total + (docType === 'invoice' ? tax : 0)) * 100) / 100;

  try {
    const [docRes, emailRes] = await Promise.all([
      generateDocument({ docType, items: lines, ...fields }),
      generateEmail({ docType, fromName: fields.fromName, toName: fields.toName, projectTitle: fields.projectTitle }),
    ]);

    document.getElementById('preview_area').innerHTML =
      '<div class="ai-badge"><div class="ai-dot"></div> Generated by AI</div>' +
      renderDocument({ docType, items: lines, ...fields, aiText: docRes.text, total, tax, grandTotal });

    generatedEmail = emailRes.text;
    document.getElementById('email_area').innerHTML =
      renderEmail(generatedEmail, { ...fields, docType });

  } catch (err) {
    document.getElementById('preview_area').innerHTML =
      `<div class="empty-state"><div class="icon">⚠️</div><h3>Generation failed</h3><p>${err.message}</p></div>`;
  }

  btn.disabled = false;
  btn.innerHTML = '<span>✦</span> Regenerate';
};

// ── Preview tabs ──────────────────────────────────────────
window.switchPreview = (tab, el) => {
  document.querySelectorAll('.preview-tabs .tab').forEach(t => t.classList.remove('active'));
  el.classList.add('active');
  document.getElementById('preview_area').style.display = tab === 'preview' ? 'block' : 'none';
  document.getElementById('email_area').style.display   = tab === 'email'   ? 'block' : 'none';
};

// ── Copy email ────────────────────────────────────────────
window.copyEmail = () => {
  if (!generatedEmail) return alert('Generate a document first!');
  navigator.clipboard.writeText(generatedEmail).then(() => {
    const btn = document.querySelector('.action-btn.primary');
    btn.textContent = '✓ Copied!';
    setTimeout(() => btn.textContent = 'Copy email', 2000);
  });
};

// ── Payment ───────────────────────────────────────────────
window.showUpgrade = () => {
  document.getElementById('upgrade_modal').style.display = 'flex';
};

window.payWithStripe = async () => {
  const email = document.getElementById('pay_email').value.trim();
  if (!email) return alert('Enter your email first');
  try { await startStripeCheckout(email); }
  catch (e) { alert('Stripe error: ' + e.message); }
};

window.payWithPaystack = async () => {
  const email    = document.getElementById('pay_email').value.trim();
  const currency = document.getElementById('pay_currency').value;
  if (!email) return alert('Enter your email first');
  try { await startPaystackCheckout(email, currency); }
  catch (e) { alert('Paystack error: ' + e.message); }
};

// ── Helpers ───────────────────────────────────────────────
function val(id) { return document.getElementById(id)?.value || ''; }
